#!/bin/bash

# If python3 command doesn't exist
if ! [ -x "$(command -v python3)" ]; then
	# If user built python3 command doesn't exist
	if ! [ -x "$(command -v $OPENSHIFT_DATA_DIR/bin/python3)" ]; then
		cd $OPENSHIFT_DATA_DIR;
		rm -rf tmp;
		mkdir tmp;
		cd tmp;
		wget https://www.python.org/ftp/python/3.5.1/Python-3.5.1.tar.xz;
		tar -xf Python-3.5.1.tar.xz;
		mv Python-3.5.1/* .;
		rm -rf Python-3.5.1;
		./configure --prefix=$OPENSHIFT_DATA_DIR;
		make && make install;
		cd ..;
		rm -rf tmp;
	fi

	# Create .bash_profile if not exist
	if ! [ -f "$OPENSHIFT_DATA_DIR/.bash_profile" ]; then
		touch $OPENSHIFT_DATA_DIR/.bash_profile;
	fi

	# Add export statement in .bash_profile if not exist
	if ! grep -Fxq "export PATH=\$OPENSHIFT_DATA_DIR/bin:\$PATH" $OPENSHIFT_DATA_DIR/.bash_profile; then
		echo -e "\n" >> $OPENSHIFT_DATA_DIR/.bash_profile;
		echo "export PATH=\$OPENSHIFT_DATA_DIR/bin:\$PATH" >> $OPENSHIFT_DATA_DIR/.bash_profile;
	fi
fi