#!/bin/bash
source $OPENSHIFT_CARTRIDGE_SDK_BASH

if [ $OPENSHIFT_APP_NAME = "diy" ]; then
	CMD="python3"
else
	CMD="httpd"
fi

if [ -z "$(ps -ef | grep "$(CMD)" | grep -v grep)" ]
then
    client_result "Application is already stopped"
else
    kill `ps -ef | grep "$(CMD)" | grep -v grep | awk '{ print $2 }'` > /dev/null 2>&1
fi
